name: reorganize

on:
  push:
    paths:
      - 'Data Structures & Algorithms/**'

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Configure git
        run: git config --global --add safe.directory /github/workspace

      - name: Run reorganize script
        run: python reorganize.py

      - name: Commit and push reorganized file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/
          git commit -m "reorganize: move submission to src/"
          git push